---
- hosts: all
  become: yes
  become_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python3
    pg_auth:
      user: vagrant
      password: vagrant
  tasks:
    - name: Install postgresql-contrib
      apt: 
        update_cache: yes
        state: present
        name: postgresql
    - name: Install psycopg2
      apt: 
        update_cache: yes
        state: present
        name: python3-psycopg2
    - name: Install postgresql
      apt: 
        update_cache: yes
        state: present
        name: postgresql
    - name: Add postgres user
      become: yes
      become_user: postgres
      postgresql_user:
        name: "{{ pg_auth['user'] }}"
        password: "{{ pg_auth['password'] }}"
        role_attr_flags: "CREATEDB,SUPERUSER"

