call plug#begin('~/.vim/plugged')                                                       
  Plug 'sukima/xmledit', {'branch': 'master'}                                           
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
  Plug 'sheerun/vim-polyglot'
  Plug 'whatyouhide/vim-gotham'
 call plug#end()                                                                         
                                                                                        
function! s:check_back_space() abort                                                    
  let col = col('.') - 1                                                                
  return !col || getline('.')[col - 1]  =~ '\s'                                         
endfunction                                                                             
                                                                                        
inoremap <silent><expr> <Tab>                                                           
      \ pumvisible() ? "\<C-n>" :                                                       
      \ <SID>check_back_space() ? "\<Tab>" :                                            
      \ coc#refresh()                                                                   
                                                                                        
inoremap jk <ESC>

set colorcolumn=88                                                                      
set hlsearch                                                                            
set nowrap                                                                              
set nu                                                                                  
set tabstop=2                                                                           
set softtabstop=2                                                                       
set shiftwidth=2                                                                        
set textwidth=0                                                                         
set expandtab                                                                           
set autoindent                                                                          
set fileformat=unix
silent! colorscheme gotham256

" show info on hover
nnoremap <silent> K :call <SID>show_documentation()<CR>
function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction

" navigate errors
try
    nmap <silent> <Leader>n :call CocAction('diagnosticNext')<cr>
    nmap <silent> <Leader>b :call CocAction('diagnosticPrevious')<cr>
endtry



" ==================== Cheatsheet =================================
" SHIFT + K -> show info of object under the cursor
" <Leader> is \
